package se.hkr.e7;

enum Location {
    BLEKINGE, DALARNA, GOTLAND, GÄVLEBORG, HALLAND, JÄMTLAND,
    JÖNKÖPING, KALMAR, KRONOBERG, NORRBOTTEN, SKÅNE, STOCKHOLM, SÖDERMANLAND,
    UPPSALA, VÄRMLAND, VÄSTERBOTTEN, VÄSTERNORRLAND, VÄSTMANLAND, VÄSTRA_GÖTALAND,
    ÖREBRO, ÖSTERGÖTLAND
}
