package se.hkr.e7;

public enum Location {
    BLEKINGE, DALARNA, GOTLAND, GAVLEBORG, HALLAND, JAMTLAND,
    JONKOPING, KALMAR, KRONOBERG, NORRBOTTEN, SKANE, STOCKHOLM, SODERMANLAND,
    UPPSALA, VARMLAND, VASTERBOTTEN, VASTERNORRLAND, VASTMANLAND, VASTRAGOTALAND,
    OREBRO, OSTERGOTLAND,Non
}
